### ISSUE TITLE
COPY dans le fichier SQL

### ISSUE THREAD

**Issue by nadineprofesseur** [cegepmatane/projet-integrite-2018-Yosirokun#1]
Corriger le fichier SQL en utilisant cette procédure 
https://docs.google.com/presentation/d/1wgC7BLUYG03NhlxPf1bETCrUEcHLA7-TICV54YkaRow/edit#slide=id.g289801d67e_0_34

**Comment by Yosirokun** [comment]
contenu dans le dernier commit
